version: 0.2


phases:
  build:
    #run-as: ec2-user
    commands:
      - echo Build...
      - npm install
      - ng build

  # post_build:
  #   commands:
  #     - echo Post Build...
  #     - cd /var/www/html
  #     - ng build
  #     - rm -rf ./
  #     - cp -R ./dist/test/ ./


artifacts:
  files:
    - 'dist/test/**/*'
  # base-directory: base_dir
  # name: build-artifact-name
  # discard-paths: no

  secondary-artifacts:
    ARTIFACT1:  
      base-directory: ./
      files:
        - appspec.yml
      name: code_commit_configuration