version: 0.2


phases:
  build:
    #run-as: ec2-user
    commands:
      - echo Building...
      #- cd test
      - npm install
      - ng build


artifacts:
  files:
    - '**/*'
  # base-directory: base_dir
  # name: build-artifact-name
  # discard-paths: no