version: 0.2


phases:
  build:
    #run-as: ec2-user
    commands:
      - echo Build...
      #- chmod -R 777 /var/www/html
      #- cd test
      - npm install
      #- ng build

  #post_build:
    #commands:
      #- echo Post Build...
      #- cd /var/www/html
      #- ng build
      #- rm -rf ./
      #- cp -R ./dist/test/ ./


artifacts:
  files:
    - '**/*'
  # base-directory: base_dir
  # name: build-artifact-name
  # discard-paths: no